# Generated by Django 2.0.1 on 2018-01-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0002_auto_20171123_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='phone_number',
        ),
    ]
