# Generated by Django 3.2.14 on 2022-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0003_remove_orgunit_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
