# Generated by Django 3.2.25 on 2024-04-18 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("dusken", "0006_orgunit_discord_role"),
        ("dusken", "0007_rename_discord_role_orgunit_discord_role_id"),
        ("dusken", "0008_groupprofile_discord_role_id"),
        ("dusken", "0009_remove_orgunit_discord_role_id"),
        ("dusken", "0010_auto_20240418_2132"),
        ("dusken", "0011_groupdiscordrole_discord_id_group_profile_unique"),
        ("dusken", "0012_userdiscordprofile"),
        ("dusken", "0013_alter_userdiscordprofile_user"),
        ("dusken", "0014_alter_userdiscordprofile_discord_id"),
        ("dusken", "0015_remove_duskenuser_discord_id"),
    ]

    dependencies = [
        ("dusken", "0005_duskenuser_discord_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDiscordRole",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("discord_id", models.IntegerField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "group_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_roles",
                        to="dusken.groupprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="groupdiscordrole",
            constraint=models.UniqueConstraint(
                fields=("discord_id", "group_profile"), name="discord_id_group_profile_unique"
            ),
        ),
        migrations.CreateModel(
            name="UserDiscordProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("discord_id", models.IntegerField(unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="duskenuser",
            name="discord_id",
        ),
    ]
