# Generated by Django 3.2.25 on 2024-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0005_duskenuser_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='discord_role',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
