# Generated by Django 4.2.11 on 2024-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dusken", "0006_discord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupdiscordrole",
            name="discord_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="userdiscordprofile",
            name="discord_id",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
