# Generated by Django 3.2.25 on 2024-04-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0006_orgunit_discord_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgunit',
            old_name='discord_role',
            new_name='discord_role_id',
        ),
    ]
