# Generated by Django 4.2.11 on 2024-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dusken", "0007_alter_groupdiscordrole_discord_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
    ]
