# Generated by Django 3.2.25 on 2024-04-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0008_groupprofile_discord_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='discord_role_id',
        ),
    ]
