# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0008_auto_20160323_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='extra_data',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
