# Generated by Django 4.2.13 on 2024-07-05 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dusken", "0008_membershiptype_stripe_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_source",
            field=models.CharField(choices=[("app", "App"), ("web", "Web")], default="web", max_length=3),
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("stripe_id", models.CharField(db_index=True, max_length=500)),
                (
                    "stripe_model",
                    models.CharField(
                        choices=[("checkout_session", "Checkout Session"), ("payment_intent", "Payment Intent")],
                        default="checkout_session",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(choices=[("app", "App"), ("web", "Web")], default="web", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("complete", "Complete"), ("expired", "Expired")],
                        default="open",
                        max_length=8,
                    ),
                ),
                (
                    "membership_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dusken.membershiptype"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
