# Generated by Django 6.0.3 on 2026-03-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dusken", "0009_order_payment_source_stripepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Order of appearance in frontend"),
        ),
    ]
