# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0010_membercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='duskenuser',
            name='phone_number_validated',
            field=models.BooleanField(default=False),
        ),
    ]
