# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0013_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='dusken.Payment'),
        ),
    ]
