# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0014_auto_20160409_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
