# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:33
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0017_auto_20160924_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duskenuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
