# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0018_auto_20160924_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='is_default_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
