# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0019_auto_20160925_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptype',
            old_name='is_default_type',
            new_name='is_default',
        ),
    ]
