# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0021_membershiptype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(365), null=True),
        ),
    ]
