# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 08:31
from __future__ import unicode_literals

from django.db import migrations


def delete_tokens(apps, schema_editor):
    Token = apps.get_model('authtoken', 'Token')
    Token.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0023_auto_20160925_0133'),
    ]

    operations = [
        migrations.RunPython(delete_tokens, reverse_code=migrations.RunPython.noop)
    ]
