# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import dusken.utils


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0024_delete_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='duskenuser',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duskenuser',
            name='email_key',
            field=models.CharField(default=dusken.utils.create_email_key, max_length=40),
        ),
    ]
