# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0025_auto_20161005_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeofstudy',
            options={'verbose_name': 'Place of study', 'verbose_name_plural': 'Places of study'},
        ),
    ]
