# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import mptt.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0026_auto_20170412_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duskenuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='legacy id'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='place_of_study',
            field=models.ManyToManyField(blank=True, to='dusken.PlaceOfStudy', verbose_name='place of study'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='street_address_two',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street address 2'),
        ),
        migrations.AlterField(
            model_name='duskenuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='stripe customer id'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='card_number',
            field=models.IntegerField(unique=True, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='registered_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registered datetime'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membercards', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='admin_groups',
            field=models.ManyToManyField(blank=True, related_name='admin_orgunits', to='auth.Group', verbose_name='admin roups'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='member_orgunits', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dusken.OrgUnit', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='short_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='placeofstudy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='placeofstudy',
            name='short_name',
            field=models.CharField(max_length=16, verbose_name='short name'),
        ),
    ]
