# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('dusken', '0027_auto_20170412_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='admin_groups',
        ),
        migrations.RemoveField(
            model_name='orgunit',
            name='groups',
        ),
        migrations.AddField(
            model_name='orgunit',
            name='admin_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_orgunits', to='auth.Group', verbose_name='admin group'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_orgunits', to='auth.Group', verbose_name='group'),
        ),
    ]
