# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0029_auto_20170531_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membercard',
            old_name='registered_datetime',
            new_name='registered',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='does_not_expire',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='expiry_type',
            field=models.CharField(choices=[('duration', 'Duration'), ('never', 'Never'), ('end_of_year', 'End of year')], default='duration', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_data',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='f.ex phone_number, card_number, one time code, etc'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('app', 'Mobile app'), ('sms', 'SMS'), ('card', 'Credit card'), ('physical_card', 'Physical card'), ('other', 'Other')], default='other', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
