# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0030_auto_20170708_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duskenuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='duskenuser',
            name='created',
        ),
    ]
