# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0031_auto_20170709_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'User log messages',
                'verbose_name': 'User log message',
            },
        ),
        migrations.AlterModelOptions(
            name='duskenuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'verbose_name': 'Group profile'},
        ),
        migrations.AlterModelOptions(
            name='membercard',
            options={'verbose_name': 'Member card'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'verbose_name': 'Membership type'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orgunit',
            options={'verbose_name': 'Org unit'},
        ),
        migrations.AlterField(
            model_name='membercard',
            name='registered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registered'),
        ),
        migrations.AddField(
            model_name='userlogmessage',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlogmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
