# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0032_auto_20170709_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgunit',
            options={'verbose_name': 'Org unit', 'verbose_name_plural': 'Org units'},
        ),
        migrations.AddField(
            model_name='orgunit',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='contact person'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='website'),
        ),
    ]
