# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0034_orgunitlogmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='posix_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_cards', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
