# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0035_auto_20170709_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duskenuser',
            name='place_of_study',
        ),
        migrations.AddField(
            model_name='duskenuser',
            name='place_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dusken.PlaceOfStudy', verbose_name='place of study'),
        ),
    ]
