# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('dusken', '0037_auto_20170714_1710'), ('dusken', '0038_auto_20170714_1744')]

    dependencies = [
        ('dusken', '0036_auto_20170710_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duskenuser',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='membercard',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Member card'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
    ]
