# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0037_view_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
