# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0038_auto_20170716_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='order',
            name='member_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dusken.MemberCard'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
