# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0039_auto_20170716_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
