# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:59
from __future__ import unicode_literals

from django.db import migrations
import uuid


def set_dummy_slugs(apps, schema_editor):
    MembershipType = apps.get_model('dusken', 'MembershipType')
    for row in MembershipType.objects.all():
        name_to_slug = {
            'Membership': 'standard',
            'Life long': 'lifelong',
            'Trial membership': 'trial'
        }
        row.slug = name_to_slug.get(row.name) or uuid.uuid4()
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0040_membershiptype_slug_part_1'),
    ]

    operations = [
        migrations.RunPython(set_dummy_slugs, reverse_code=migrations.RunPython.noop),
    ]
