# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0041_membershiptype_slug_part_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
