# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0042_membershiptype_slug_part_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='type',
            field=models.CharField(choices=[('volunteers', 'Volunteers'), ('', 'Standard')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.Group'),
        ),
    ]
