# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0044_auto_20170727_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duskenuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
