# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0045_auto_20170727_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duskenuser',
            old_name='phone_number_validated',
            new_name='phone_number_confirmed',
        ),
        migrations.AddField(
            model_name='duskenuser',
            name='phone_number_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duskenuser',
            name='phone_number_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
