# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0048_auto_20170804_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeofstudy',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='short name'),
        ),
    ]
