# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0049_auto_20170810_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duskenuser',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
