# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0050_auto_20170810_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duskenuser',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
