# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusken', '0051_auto_20170810_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'verbose_name': 'Group profile', 'verbose_name_plural': 'Group profiles'},
        ),
        migrations.AlterModelOptions(
            name='membercard',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Member card', 'verbose_name_plural': 'Member cards'},
        ),
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'verbose_name': 'Membership type', 'verbose_name_plural': 'Membership types'},
        ),
    ]
