variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  POSTGRES_DB: dusken
  CELERY_BROKER_URL: "redis://redis:6379/0"

services:
  - redis:latest

default:
  image: nikolaik/python-nodejs:python3.8-nodejs16
  cache:
    paths:
      - .cache/pip
      - .venv
      - frontend/node_modules

build_frontend:
  stage: test
  script:
    - bin/build-frontend

tests:
  stage: test
  before_script:
    - apt-get update && apt-get install libsasl2-dev libldap2-dev -y
    - poetry config virtualenvs.in-project true
    - poetry run pip install -U pip wheel
    - poetry install
  script:
    - bin/ensure-python-deps.sh
    - poetry run python manage.py migrate
    - poetry run python manage.py check
    - poetry run coverage run --source=dusken,apps --omit=dusken/migrations/*,apps/*/migrations/* -m pytest -v
    - poetry run coverage report
    - poetry run coverage xml
    - poetry run bin/lint
  coverage: '/^TOTAL.+?\d+\%$/'
  artifacts:
    reports:
      cobertura: coverage.xml

deploy:
  stage: deploy
  before_script:
     # Install ssh if not already
     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
     - eval $(ssh-agent -s)
     # Make SSH key available
     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
     # Add known host keys
     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
     - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh gitdeploy@dreamcast.neuf.no "$(< bin/deploy)"
  only:
    - main
