# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.3'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.16.0"
    hooks:
      - id: django-upgrade
