[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "duskensite.settings.dev"

[tool.black]
line-length = 120
target_version = ['py38']

[tool.isort]
profile = "black"
line_length = 120

[tool.poetry]
name = "galtinn"
version = "0.1.0"
description = ""
authors = ["EDB <edb@neuf.no>"]
license = "MIT"

[tool.poetry.dependencies]
argon2-cffi = "21.3.*"
celery = "5.2.*"
coreapi = "2.3.*"
dj-database-url = "0.5.*"
Django = "3.2.*"
django-bootstrap5 = "21.3"
django-countries = "7.3.*"
django-extensions = "3.1.*"
django-filter = "21.1"
django-inline-svg = "0.1.*"
django-ldapdb = "1.5.*"
django-mptt = "0.13.*"
django-phonenumber-field = "6.1.*"
django-recaptcha = "3.0.*"
django-redis = "5.2.*"
django-select2 = "7.10.*"
django-signal-disabler = "0.1.*"
djangorestframework = "3.13.*"
fabric = "2.7.*"
gunicorn = "20.1.*"
Markdown = "3.3.*"
mysqlclient = "2.1.*"
passlib = "1.7.*"
phonenumbers = "8.12.*"
psycopg2 = "2.9.*"
python = "~3.8"
redis = "4.2.*"
requests = "2.27.*"
sentry-sdk = "1.5.*"
stripe = "2.72.*"
strawberry-graphql = "0.107.*"
strawberry-graphql-django = "0.2.*"

[tool.poetry.dev-dependencies]
pytest = "*"
black = "22.3.0"
pytest-django = "*"
pre-commit = "*"
isort = "*"
codecov = "2.1.*"
requests-mock = "1.9.*"
pycln = "^1.3.1"
pytest-cov = "^3.0.0"
pyupgrade = "^2.37.2"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
