# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailchimpsubscription',
            options={'verbose_name': 'mailchimp subscription', 'verbose_name_plural': 'mailchimp subscriptions'},
        ),
    ]
