# Generated by Django 3.2.16 on 2024-04-02 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailchimp", "0004_auto_20170803_1607"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailChimpSubscription",
        ),
    ]
