# Generated by Django 1.11.3 on 2017-08-03 14:07
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuf_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authprofile",
            name="created",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="authprofile",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
