# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuf_auth', '0003_authprofile_username_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authprofile',
            name='username_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
