# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuf_auth', '0004_auto_20170814_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authprofile',
            name='username_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
